// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

//Static

//Filled manually
Table ORGANISM {
  TAXCODE integer [primary key]
  NAME text
}

Table MODIFICATION {
  MODIFICATION_ID integer [primary key]
  NAME text
  SYMBOL text
}

Table PROTEASE {
  PROTEASE_ID integer [primary key]
  NAME text
  CLEAVAGE_RULE text //Regex that specifies the cleavage rule of that protease

}

Table OMIC{
  OMIC_ID integer [primary key]
  NAME text [not null]
}

Table ENRICHMENT_TYPE{
 ENRICHMENT_TYPE_ID integer [primary key]
 NAME text [not null] 
 DESCRIPTION text [not null] 
 REFERENCE text [not null] 
 SHORT text [not null] 
 ENRICHMENT_CLASS text [not null]
}

Table ENRICHMENT_TYPE_TO_OMIC{
  ENRICHMENT_TYPE_ID integer [ref: > ENRICHMENT_TYPE.ENRICHMENT_TYPE_ID]
  OMIC_ID integer [ref: > OMIC.OMIC_ID]
    indexes {
    (ENRICHMENT_TYPE_ID, OMIC_ID) [pk]
    }
}

Table ENZYME_CLASS{
  ENZYME_CLASS_ID integer [primary key]
  NAME text [not null]
}

//Filled via a script
Table PROTEIN {
  PROTEIN_ID integer [primary key]
  UNIPROT_ACC text [not null]
  GENE_NAME text [not null]
  TAXCODE integer [not null, ref: > ORGANISM.TAXCODE]
  PARENT_PROTEIN_ID integer [ref: > PROTEIN.PROTEIN_ID]
}

Table PEPTIDE {
  PEPTIDE_ID integer [primary key]
  SEQUENCE text
  
}

Table PROTEIN_TO_PEPTIDE {
  PROTEIN_ID integer [ref: > PROTEIN.PROTEIN_ID]
  PEPTIDE_ID integer [ref: > PEPTIDE.PEPTIDE_ID]
  PROTEASE_ID integer [ref: > PROTEASE.PROTEASE_ID]
  START_POSITION integer [not null]
  END_POSITION integer [not null]
  // MISSED_CLEAVAGES integer [not null] //I do not need this for anything
    indexes {
    (PROTEIN_ID, PEPTIDE_ID) [pk]
    }
}


//
//Table MODIFIED_PEPTIDE {
//  MODIFIED_PEPTIDE_ID integer [primary key]
//  PEPTIDE_ID integer [not null, ref: > PEPTIDE.PEPTIDE_ID]
//  MODIFIED_SEQUENCE text [not null]
//  //MODIFICATION_TYPE //Would be awkward, since a peptide can have multiple types of mod
//  }



Table MODIFIED_SITE {
 MODIFIED_SITE_ID integer [primary key]
 PROTEIN_ID integer [not null, ref: > PROTEIN.PROTEIN_ID]
 MODIFICATION_ID integer [not null, ref: > MODIFICATION.MODIFICATION_ID]
 POSITION integer [not null]
 RESIDUE text [not null]
 SITE_IDENTIFIER text //Composed of e.g. Uniprot + Residue + Position - only if otherwise not performant, else remove
}

Table ENZYME_SUBSTRATE_RELATIONSHIP{
  ENZYME_PROTEIN_ID integer [ref: > PROTEIN.PROTEIN_ID]
  SUBSTRATE_SITE_ID integer [ref: > MODIFIED_SITE.MODIFIED_SITE_ID]
  ENZYME_CLASS_ID integer [not null, ref: > ENZYME_CLASS.ENZYME_CLASS_ID]

      indexes {
    (ENZYME_PROTEIN_ID, SUBSTRATE_SITE_ID) [pk]
    }
}



//Dynamic -- TODO: Do Pre-Existing Datasets need their own tables? 
//If not, you could rename and remove the user prefix or so
//But then there are datasets without user

Table USER {
  USER_ID integer [primary key]
  SESSION_ID text
  LAST_ACCESSION_DATE text
}

Table USER_DATASET {
  DATASET_ID integer [primary key]
  NAME text [not null]
  USER_ID integer [not null, ref: > USER.USER_ID]
  DATASET_TYPE text [not null, note: 'One of: FoldChange/Curve']
  OMICS text [not null, note: 'One of: Phosphorylation/Protein/Other']
  TAXCODE integer [not null, ref: > ORGANISM.TAXCODE]
}


//TODO: Lowercase integer and text
Table USER_QUANTIFICATION_DATA {
  USER_DATUM_ID INTEGER [primary key]
  DATASET_ID INTEGER [not null, ref: > USER_DATASET.DATASET_ID]
  REGULATION TEXT [not null, note: 'One of: up/down/-'] //Could instead do up/down/not/nan or allow NULL
  USER_CURVE_ID INTEGER
  PROTEIN_ID INTEGER
  PEPTIDE_ID INTEGER //Null if site level
  //No direct columns for modified peptide or sites. Because a) we don't have modified peptide ids anymore and b) Modified Site IDs might be many-to-many. So instead we add key-value pairs into UDD table and put modified sequence as string here
  MODIFIED_SEQUENCE TEXT //Null if site level
  //MODIFIED_PEPTIDE_ID INTEGER //Null if site level or unmodified peptide
  //MODIFIED_SITE_ID INTEGER //Null if peptide level 

}


Table USER_DATUM_DETAIL {
  USER_DATUM_ID INTEGER [not null, ref: > USER_QUANTIFICATION_DATA.USER_DATUM_ID]
  KEY TEXT [not null]
  VALUE TEXT
}


Table USER_CURVE_DATA {
  USER_CURVE_ID integer [not null, ref: > USER_QUANTIFICATION_DATA.USER_CURVE_ID] //Not sure if this ref works since USER_CURVE_ID is not a primary key (is it a candidate key tho?)
  FACTOR_NAME text [not null] //E.g. dose, temperature, time
  FACTOR_VALUE real [not null]
  FACTOR_UNIT text [not null] //E.g. nM, h
  RESPONSE_VALUE real [not null]
}


Table USER_DATASET_ENRICHMENT_RESULT {
  DATASET_ID integer [not null, ref: > USER_DATASET.DATASET_ID] //TODO: No need to put UUID_ID here, but via joins you should still make sure the user has the correct uuid_id 
  ENRICHMENT_TYPE_ID integer [not null, ref: > ENRICHMENT_TYPE.ENRICHMENT_TYPE_ID]
  ENRICHMENT_JSON blob [not null]
}


